dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: MuUKmZIkSBK7QknF57galtpY4G8TwpzAcmsx2PlIebs9rW96xDYPrSTV6jOwVeZSBPRQK2v25EoNkOiuHufv4cyjtY9VYlycYkRI2k5hhOwC45eVD036EnqWuJpGRo7yXjxhQi6aGUaO492UoQsRSBvD6sNeaQAbs2er2C0rDAxaNCZxefdAeZHnkbODWbkmW9UWjfcmtISGtYh+2+j3nnGQAR8OLpiNZusx9V8MNN+ulRfpIqU/UBLVDOq3tlDac0tFAKw7vugCVWs+bfC9s3dsgfGl4Q9fxW7OZq7eVi9bqk0HZaEF6wUJlWIOggUadX6eMpRSzUtunID+UAFM0WnZm6fnl0MlZwGz03tOLVPi7xx8/RCEQEEI0XrhiFlFpFipZqdp6Oc83IMt2wIW77uEZ+d8wp4m70XihFzWPK5mTJkb+Jpj80rqNIp5TAduq1PeCXhZ+aARYS7cVIyQGu1on+hNY9xPbOOq4YGdqZpmW/4diALJfbB4cN2zgpiOiKQWyzVuJvXb4REyn3kPLGiZV1kENeqp+vER11TvEnKDlMIRyNBft6rnO8nbnymAJlQyiZdJcxU9XKCCAxcVQx6CnU5jnt5ZXU5+o2Fkc9uTUhI2vIn2iwEfwxfinqrpYmBe1CFBZIsP6jLLKZS65NP7JHptcbuPXFZdmKAs1mg=
  file: Gerbers/MNT-102_gerbers.zip
  on:
    repo: w4xzr/MNT-102
  skip_cleanup: 'true'
